### ISSUE TITLE
Add support for `getattr` calls

### ISSUE THREAD

**Issue by Tadaboody** [asottile/dead#1]
For example running `dead` on itself yields
```
visit_ImportFrom is never read, defined in {'dead.py'}
visit_ClassDef is never read, defined in {'dead.py'}
visit_AsyncFunctionDef is never read, defined in {'dead.py'}
visit_Assign is never read, defined in {'dead.py'}
visit_Name is never read, defined in {'dead.py'}
visit_Attribute is never read, defined in {'dead.py'}
visit_Str is never read, defined in {'dead.py'}
```
Even though they are all read by `NodeVisitor.visit` 
https://github.com/python/cpython/blob/master/Lib/ast.py#L250-253

**Comment by asottile** [comment]
It's more than just getattr, dead doesn't currently try to do anything with base classes : https://github.com/asottile/dead#false-positives

**Comment by Tadaboody** [comment]
Right. but I'll start with adding `getattr` support for now to see if I understand the code 😃
