### ISSUE TITLE
separate "non-dead" annotations from the code

### ISSUE THREAD

**Issue by petergaultney** [asottile/dead#165]
We have a lot of dead code that this tool catches beautifully. Thank you!

We also have a lot of not-actually-dead code, or "yes technically that's dead but there's a good reason why it's there". 

Unfortunately, I don't have the stomach for adding `# dead: disable` to all the places where this is the case. It would be a _lot_ of changes that would make the code harder to read.

Would you be open to supporting as an input a "ignore_filelines" file? I'm thinking newline separated, in exactly the format you already use (`fully/qualified/filename.py:<linum>`), that would essentially pre-populate `visitor.disabled` (probably right after construction: https://github.com/asottile/dead/blob/main/dead.py#L310)?

This would let me keep our code separate from our linting. I _think_ it would pretty much 'just' work, but I haven't fully grokked your code.

Let me know - if so, I'd like to make a PR and get this working!

**Comment by asottile** [comment]
sounds complicated.  you may want to explore your own version of an allowlist separate from the tool

I don't really think I want to carry that complexity here though

**Comment by petergaultney** [comment]
huh, okay. Maybe I'm not communicating the idea clearly, or maybe I just misunderstand how your code works. I was imagining the implementation would be pretty much literally:

`visitor.disabled = open(args.disabled_filelines_txt).read().splitlines()`
