### ISSUE TITLE
Unused parameters from framework

### ISSUE THREAD

**Issue by trivialkettle** [asottile/dead#172]
Hi,
I use a framework that uses callbacks with some parameters I do not need in some cases. `dead` always shows them as unused (and they are). Would it be possible to have a solution like [pylint](https://pycodequ.al/docs/pylint-messages/w0613-unused-argument.html#how-to-fix) has to avoid `dead` reporting them?

From pylint docs:

```
# fix for positional arguments: prepend _
def example1(_foo):
    return 1

# fix for keyword args: catch into _
def example2(used_kw_arg=1, **_):
    return used_kw_arg + 1

# fix for a single keyword arg: delete it
def example2(used_kw_arg=1, another_kw_arg=2):
    del another_kw_arg
    return used_kw_arg + 1
```

I tried the first and last solution with `dead` and it still reports the parameters.

Best regards

**Comment by asottile** [comment]
yeah there's currently no solution for this, dead doesn't attempt to be perfect (it's impossible given the information it has access to) -- just a tool to help you discover dead code
