### ISSUE TITLE
Detect unused arguments

### ISSUE THREAD

**Issue by cjerdonek** [asottile/dead#23]
A related feature that could be useful would be to detect "dead arguments," or function arguments not used by the function body.

Here is an example of a dead argument found in pip: https://github.com/pypa/pip/pull/7015

**Comment by asottile** [comment]
definitely doable! potentially has the same issue as inheritance methods for false positives but probably still worth it

**Comment by cjerdonek** [comment]
> false positives

Yeah, but just seeing the list of possibilities could help!

**Comment by asottile** [comment]
#24 is a first stab at this, it doesn't actually detect the particular case because dead doesn't know about scopes yet (it assumes all symbols are global for now)
