### ISSUE TITLE
Django support

### ISSUE THREAD

**Issue by C0DK** [asottile/dead#33]
So it might be rather difficult to do, and i get the "i wrote it on an airplane" - but i like the idea of the code. However it doesn't really work with Django (i got a million deadcode things like my settings constants etc)

**Comment by asottile** [comment]
I'm not going to write django-specific knowledge into the tool but if you can come up with heuristics which apply more broadly then sure

there's also `# dead: disable` if you need to mark something as "yes this is actually used despite weirdness"

**Comment by asottile** [comment]
also note if you need to exclude specific files you an use `--exclude '/settings\.py$' for instance
